### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by katou-kaede** [katou-kaede/portfolio#33]
■Webアプリの概要
イベントやゲーム、あそびなどの参加者募集を簡単に行えるサービスです。大人数のLINEグループであそびやイベントの誘いを発言するのは少し勇気がいったり、人数が集まりすぎたときに断らなくてはならなくなったり、一人一人に声をかけるのが面倒だったり、何かを主催しようとしたときに発生する手間を解決できればいいなと思っています。
参加者側も、自分が参加したいものに対してのみ参加リクエストを送信すればよく、すべてに出欠回答をしなくていいという点が利点となります。
また、限定公開の個人間のあそびから、一般公開の大規模イベントまで対応できることが特徴です。
特定のグループ全員の出欠確認・日程調整ができるサービスはよく見かけますが、 そうではなく、「やりたいこと」を「そのとき誘いたい人だけ」に提示することができるサービスを考えています。

■1週間辺りの開発に向けられる時間
- 1週間あたり：15～20時間

■ProjectsのURL
https://github.com/users/katou-kaede/projects/1/views/1

■MVPリリースまで
- [ ] アプリケーションの立ち上げ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] パスワードリセット機能
- [ ] マイページ
- [ ] プロフィール編集、削除
- [ ] アカウント編集、削除
- [ ] イベント作成
- [ ] イベント編集、削除
- [ ] イベント一覧
- [ ] イベント詳細
- [ ] イベント検索、絞り込み機能
- [ ] 主催のイベント詳細
- [ ] ユーザー一覧
- [ ] ユーザー詳細
- [ ] ユーザー検索、絞り込み機能
- [ ] グループ一覧
- [ ] グループ詳細
- [ ] 友だち登録機能
- [ ] グループ作成
- [ ] グループ編集、削除
- [ ] グループ検索機能
- [ ] デプロイ

■MVP後
- [ ] LINE通知
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] ファビコン
- [ ] レスポンシブ対応

■MVPレビュー依頼予定日
予定日：2024年12月16日

**Comment by TakenakaEri** [comment]
お疲れ様です！issueの内容を確認しました〜
以下2点のご確認をお願いいたします！

**- デプロイについて**

デプロイに関してですが、アプリを作成し終わった後にデプロイを予定しているように見受けられますが、デプロイはrails newをしてTopページへのルーティング設定をしたくらいのタイミングで行ってください。
アプリを完成させてからデプロイする場合、ローカル環境では出ないエラーが複数発生しても原因を究明することが困難となります。

**- ストーリーポイントが３以上のタスクに関して**

ストーリーポイントが5のものがいくつか見受けられますが、ストーリーポイントは３以下に設定してください。ポイントが大きめのものは長時間の開発が必要になるのと、途中で何かあった際に分解しづらくなります。今の段階でタスクを分解して３以下に設定をお願いします。
また、調査の時間が必要な場合は、別で調査用のタスクを切ってください

**Comment by katou-kaede** [comment]
ご確認ありがとうございます！
https://github.com/users/katou-kaede/projects/1/views/1

- デプロイのタイミングを修正しました。（デプロイについてほとんどわからないのですが、聞きたいことが出てきた場合技術面談を使わせていただくことは可能なのでしょうか？）
- ストーリーポイントが３以上のタスクに関して、分解し最大3となるようにしました。

よろしくお願いいたします。

**Comment by kashiwagi-rena** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- 友だち登録機能
- ユーザー検索、絞り込み機能
- ユーザー一覧
- パスワードリセット機能
