### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by katou-kaede** [katou-kaede/portfolio#83]
## 各種情報
**サービスの概要：**
イベントやゲーム、あそびなどの参加者募集を簡単に行えるサービスです。大人数のLINEグループであそびやイベントの誘いを発言するのは少し勇気がいったり、人数が集まりすぎたときに断らなくてはならなくなったり、一人一人に声をかけるのが面倒だったり、何かを主催しようとしたときに発生する手間を解決できればいいなと思っています。
参加者側も、自分が参加したいものに対してのみ参加リクエストを送信すればよく、すべてに出欠回答をしなくていいという点が利点となります。
また、限定公開の個人間のあそびから、一般公開の大規模イベントまで対応できることが特徴です。
特定のグループ全員の出欠確認・日程調整ができるサービスはよく見かけますが、 そうではなく、「やりたいこと」を「そのとき誘いたい人だけ」に提示することができるサービスを考えています。

**MVPで検証する事柄：**

> 機能の実用性

- ユーザーが期待どおりに主要な機能を利用できるか（例：イベント作成や参加、グループ作成など）

- 主要機能が直感的に利用できるか、ユーザーが迷わずに操作できるか。

- イベントやグループ機能が適切に動作し、エラーや不具合がないか。

>  認証・セキュリティ

- 新規登録やログインが適切に行われているか。

- 非ログインユーザーが閲覧できる範囲が適切に制限されているか（一般公開イベント、限定公開イベントなどのアクセス管理）

**サービス名：** Event Station
**サービスURL：** https://event-station.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] マイページ
- [ ] プロフィール編集、削除
- [ ] アカウント編集、削除
- [ ] イベント作成
- [ ] イベント編集、削除
- [ ] イベント一覧
- [ ] イベント詳細
- [ ] ユーザー一覧
- [ ] ユーザー詳細
- [ ] ユーザー検索機能
- [ ] グループ一覧
- [ ] グループ詳細
- [ ] 友だち登録機能
- [ ] グループ作成
- [ ] グループ編集、削除

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください。なければこの項目は省略してください。

- [ ] イベント検索機能
- [ ] グループ検索機能
- [ ] パスワードリセット機能

**Comment by kenchasonakai** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
